name: Build and Test on Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  #proc_num: $(nproc)
  proc_num: 12

jobs:
  gcc-compile-with-make:
    runs-on: ubuntu-latest # https://github.com/actions/runner-images
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/install-dependences
    - name: config brpc
      run: |
           ./config_brpc.sh --header="/usr/local/include /usr/include" --libs="/usr/local/lib /usr/local/lib64 /usr/lib /usr/lib64"
    - name: compile
      run: |
           make -j ${{env.proc_num}}

  gcc-compile-with-cmake:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/install-dependences
    - name: cmake 
      run: |
           mkdir build
           cd build
           cmake ..
    - name: compile
      run: |
           cd build
           make -j ${{env.proc_num}}

  gcc-compile-with-bazel:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install dependences
      run: |
           sudo apt-get update
           sudo apt-get install libibverbs-dev
    - name: compile
      run: |
           bazel build -j ${{env.proc_num}} -c opt --copt -DHAVE_ZLIB=1 //...

  gcc-compile-with-make-all-options:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/install-all-dependences
    - name: config brpc
      run: |
           ./config_brpc.sh --header="/usr/local/include /usr/include" --libs="/usr/local/lib /usr/local/lib64 /usr/lib /usr/lib64" --with-thrift --with-glog --cxx=clang++ --cc=clang
    - name: compile
      run: |
           make -j ${{env.proc_num}}

  gcc-compile-with-cmake-all-options:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/install-all-dependences
    - name: cmake 
      run: |
           mkdir build
           cd build
           cmake -DWITH_MESALINK=OFF -DWITH_GLOG=ON -DWITH_THRIFT=ON ..
    - name: compile
      run: |
           cd build
           make -j ${{env.proc_num}}

  gcc-compile-with-bazel-all-options:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install dependences
      run: |
           sudo apt-get update
           sudo apt-get install libibverbs-dev
    - name: compile
      run: |
           bazel build -j 12 -c opt --define with_mesalink=false --define with_glog=true --define with_thrift=true --copt -DHAVE_ZLIB=1 //...


  clang-compile-with-make:
    runs-on: ubuntu-latest # https://github.com/actions/runner-images
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/install-dependences
    - name: config brpc
      run: |
           ./config_brpc.sh --header="/usr/local/include /usr/include" --libs="/usr/local/lib /usr/local/lib64 /usr/lib /usr/lib64" --nodebugsymbols --cxx=clang++ --cc=clang
    - name: compile
      run: |
           make -j ${{env.proc_num}}

  clang-compile-with-cmake:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/install-dependences
    - name: cmake 
      run: |
           export CC=clang
           export CXX=clang++
           mkdir build
           cd build
           cmake ..
    - name: compile
      run: |
           cd build
           make -j ${{env.proc_num}}

  clang-compile-with-bazel:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install dependences
      run: |
           sudo apt-get update
           sudo apt-get install libibverbs-dev
    - name: compile
      run: |
           export CC=clang
           export CXX=clang++
           bazel build -j ${{env.proc_num}} -c opt --copt -DHAVE_ZLIB=1 //...

  clang-compile-with-make-all-options:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/install-all-dependences
    - name: config brpc
      run: |
           ./config_brpc.sh --header="/usr/local/include /usr/include" --libs="/usr/local/lib /usr/local/lib64 /usr/lib /usr/lib64" --with-thrift --with-glog --cxx=clang++ --cc=clang
    - name: compile
      run: |
           make -j ${{env.proc_num}}

  clang-compile-with-cmake-all-options:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/install-all-dependences
    - name: cmake 
      run: |
           export CC=clang
           export CXX=clang++
           mkdir build
           cd build
           cmake -DWITH_MESALINK=OFF -DWITH_GLOG=ON -DWITH_THRIFT=ON ..
    - name: compile
      run: |
           cd build
           make -j ${{env.proc_num}}

  clang-compile-with-bazel-all-options:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install dependences
      run: |
           sudo apt-get update
           sudo apt-get install libibverbs-dev
    - name: compile
      run: |
           export CC=clang
           export CXX=clang++
           bazel build -j 12 -c opt --define with_mesalink=false --define with_glog=true --define with_thrift=true --copt -DHAVE_ZLIB=1 //...
