name: build on macos

on:
  push:
    branches: [ mac_flow ]
  pull_request:
    branches: [ mac_flow ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  BUILD_DIR: build

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install leveldb, gflags and protobuf
      run: |
           brew install leveldb
           brew install gflags
           brew install protobuf
           brew install openssl
           protoc --version

    - name: Build with cmake
      run: |
           mkdir ${{env.BUILD_DIR}}
           cd ${{env.BUILD_DIR}}
           cmake ..
           make -j $(sysctl -n hw.logicalcpu)
