name: build and test on macos

on:
  push:
    branches: [ ci_mac_flow ]
  pull_request:
    branches: [ ci_mac_flow ]

env:
  BUILD_TYPE: Release
  BUILD_DIR: build

jobs:
  compile-with-make:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: intall dependences
      run: |
           brew install openssl gnu-getopt coreutils gflags protobuf leveldb

    - name: config_brpc
      run: |
           GETOPT_PATH=$(find "/usr/local/Cellar/" -name "getopt" -type f -perm +111 -exec dirname {} \;)
           export PATH=$GETOPT_PATH:$PATH
           ./config_brpc.sh --header="/usr/local/include" --libs="/usr/local/lib"

    - name: compile
      run: |
           make -j $(sysctl -n hw.logicalcpu)

  compile-with-cmake:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: intall dependences
      run: |
           brew install openssl gnu-getopt coreutils gflags protobuf leveldb

    - name: cmake
      run: |
           mkdir ${{env.BUILD_DIR}}
           cd ${{env.BUILD_DIR}}
           cmake ..

    - name: compile
      run: |
           make -j $(sysctl -n hw.logicalcpu)

  compile-with-bazel:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: intall dependences
      run: |
           brew install openssl gnu-getopt coreutils gflags protobuf leveldb

    - name: compile
      run: |
           bazel build brpc -j $(sysctl -n hw.logicalcpu)

  unittest:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: intall dependences
      run: |
           brew install openssl gnu-getopt coreutils gflags protobuf leveldb googletest

    - name: config_brpc
      run: |
           GETOPT_PATH=$(find "/usr/local/Cellar/" -name "getopt" -type f -perm +111 -exec dirname {} \;)
           export PATH=$GETOPT_PATH:$PATH

    - name: compile
      run: |
           cd test
           make -j $(sysctl -n hw.logicalcpu)

    - name: test
      run: |
           sh run_tests.sh
