name: build on macos

on:
  push:
    branches: [ mac_flow ]
  pull_request:
    branches: [ mac_flow ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  BUILD_DIR: build

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install leveldb, gflags and protobuf
      run: |
           brew install openssl gnu-getopt gflags protobuf leveldb
           #brew install leveldb
           #brew install gflags
           #brew install protobuf
           #brew install openssl
           protoc --version

   #- name: compile-with-cmake
   #  run: |
   #       mkdir ${{env.BUILD_DIR}}
   #       cd ${{env.BUILD_DIR}}
   #       cmake ..
   #       make -j $(sysctl -n hw.logicalcpu)
   
    - name: compile-with-make
      run: |
           GETOPT_PATH=$(find "/opt/homebrew/Cellar/" -name "getopt" -type f -perm +111 -exec dirname {} \;)
           export PATH=$GETOPT_PATH:$PATH
           ./config_brpc.sh --header="/usr/local/include" --libs="/usr/local/lib"
           make -j $(sysctl -n hw.logicalcpu)

    - name: unittest
      run: |
           cd test
           sh run_tests.sh
