name: build and test on macos

on:
  push:
    branches: [ ci_mac_flow ]
  pull_request:
    branches: [ ci_mac_flow ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  BUILD_DIR: build

jobs:
  compile-with-make:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: intall dependences
      run: |
           brew install openssl gnu-getopt coreutils gflags protobuf leveldb googletest

   - name: compile with bazel
     run: |
          bazel build brpc -j $(sysctl -n hw.logicalcpu)

    - name: compile with make
      run: |
           GETOPT_PATH=$(find "/usr/local/Cellar/" -name "getopt" -type f -perm +111 -exec dirname {} \;)
           export PATH=$GETOPT_PATH:$PATH
           ./config_brpc.sh --header="/usr/local/include" --libs="/usr/local/lib"
           make -j $(sysctl -n hw.logicalcpu)

  compile-with-cmake:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: intall dependences
      run: |
           brew install openssl gnu-getopt coreutils gflags protobuf leveldb googletest

    - name: compile with cmake
      run: |
           mkdir ${{env.BUILD_DIR}}
           cd ${{env.BUILD_DIR}}
           cmake ..
           make -j $(sysctl -n hw.logicalcpu)

  compile-with-bazel:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: intall dependences
      run: |
           brew install openssl gnu-getopt coreutils gflags protobuf leveldb

   - name: compile with bazel
     run: |
          bazel build brpc -j $(sysctl -n hw.logicalcpu)

  unittest:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: intall dependences
      run: |
           brew install openssl gnu-getopt coreutils gflags protobuf leveldb googletest

    - name: unittest
      run: |
           cd test
           make -j $(sysctl -n hw.logicalcpu)
           sh run_tests.sh
